### ISSUE TITLE
ROS2中setuptools版本问题

### ISSUE THREAD

**Issue by fan-ziqi** [MiRoboticsLab/cyberdog_ws#1]
编译的时候会出现
```
SetuptoolsDeprecationWarning: setup.py install is deprecated. ......
```

需要将setuptools降级

```
pip install setuptools==58.2.0
```

参考
https://answers.ros.org/question/396439/setuptoolsdeprecationwarning-setuppy-install-is-deprecated-use-build-and-pip-and-other-standards-based-tools/

**Comment by Tianhonghai** [comment]
这是由于setuptools计划废弃setup.py的安装方式引起的警告，这个废弃计划并没有时间表，而Cyberdog2采用的ROS2 galactic在生成python功能包时仍然采用setup.py的安装方式，导致了这个警告的出现，目前来看没有进一步影响，可以忽略或者自行处理setuptools版本。
