### ISSUE TITLE
apt upgrade后自检失败如何恢复

### ISSUE THREAD

**Issue by tianweix** [MiRoboticsLab/cyberdog_ws#13]
ssh登录上狗后，我发现pip3有问题，运行了apt update和apt upgrade python3-pip, 重启后自检失败，雷达、gps等无法加载。有什么办法恢复到出厂设置吗

**Comment by tianweix** [comment]
语音报 “”雷达切换工作模式失败，状态异常“”

**Comment by ccap-zhy** [comment]
我也是，请问怎么解决的？

**Comment by ruheng** [comment]
您好，我们会在近期提供一套用于刷机来恢复出厂的软件镜像。请关注小米社区和github主页。祝好。
