### ISSUE TITLE
刷机包链接缺失

### ISSUE THREAD

**Issue by tianweix** [MiRoboticsLab/cyberdog_ws#14]
开发者手册中有刷机文档 https://miroboticslab.github.io/blogs/#/cn/cyberdog_flash ， 但却没有提供刷机包链接。
这是写文档时遗漏了，还是目前不支持刷机呢

**Comment by ruheng** [comment]
您好，我们会在近期提供一套用于刷机来恢复出厂的软件镜像。请关注小米社区和github主页。祝好。
