### ISSUE TITLE
我这为什么进不去ssh啊

### ISSUE THREAD

**Issue by finallyxie** [MiRoboticsLab/cyberdog_ws#34]
我通过连接笔记本的热点可以进入ssh,进入的是midesktop
但是我使用download线去连接就无法连接ssh, ping 192.168.55.1也ping不通
我通过热点进入ssh之后按照文档进入刷机模式之后又无法连接到ssh了

**Comment by ruheng** [comment]
安全考虑，系统默认ssh端口是关闭的，需要用户同意开发者协议，申请开发者、审批通过，解锁后端口才可以访问。

**Comment by finallyxie** [comment]
> 安全考虑，系统默认ssh端口是关闭的，需要用户同意开发者协议，申请开发者、审批通过，解锁后端口才可以访问。

我这里已经解锁了,但还是无法连接

**Comment by grrodre** [comment]
我尝试输入我的信息，但似乎需要一个中国的身份证。

请问是否有办法使用其他国家的身份证解锁开发者状态？

提前感谢！
