### ISSUE TITLE
LED test failed

### ISSUE THREAD

**Issue by gelato** [MiRoboticsLab/cyberdog_ws#36]
So I've got this brand new cyberdog2 as a present, and now can't use it. When I try to connect dog to the app it says error 1209 and also says in voice that LED dictionary selftest failed. No I can't do anything with it. I've also tried to access it's ssh console like described in this repo's docs, but it seems like I need some kind of developer flag on my account and I don't know how or where to get it. I'll appreciate any help with this matter, thank you!
And sorry for English in Chinese repo - this is the only international language that I know.

**Comment by ouhkedu** [comment]
手機 apps 內有通行証申請，通過後就可以用到 ssh 到狗狗，通常等兩天，不過只可以用中國人民身份証，其他証件不接受

**Comment by gelato** [comment]
谢谢你！ 最后，我修改了apk，取消了收到自检消息后强制退出并进行了OTA更新，从而恢复了系统。
