### ISSUE TITLE
cyberdog_ws 编译到 cyberdog_common的时候libcyberdog_fds.so 报错  undefined reference to `Poco::JSON::Array::Array()' 

### ISSUE THREAD

**Issue by yst-one** [MiRoboticsLab/cyberdog_ws#4]
![微信图片_20230819171540](https://github.com/MiRoboticsLab/cyberdog_ws/assets/134467913/b61e79c9-1093-4ea0-a0ff-aea4066a00be)
/usr/bin/ld: libcyberdog_fds.so: undefined reference to `Poco::JSON::Array::Array()' /usr/bin/ld: libcyberdog_fds.so: undefined reference to `Poco::JSON::Object::Object(bool)'

**Comment by WLwind** [comment]
请问您是在什么环境下编译的此仓库？我们推荐在docker上进行编译，已经安装好相关依赖项，使用方法参考：https://github.com/MiRoboticsLab/blogs/blob/rolling/docs/cn/dockerfile_instructions_cn.md
如果是在机器狗的Jetson Xavier NX上直接编译的话，需要解决一些依赖项问题，因为机器狗上的存储空间有限，我们将一些运行时不依赖的库去掉了。可以尝试用一下命令安装poco库：
`sudo apt install libpoco-dev`
