### ISSUE TITLE
请问这个codebase支持 cyberdog2 吗？

### ISSUE THREAD

**Issue by lewnus** [MiRoboticsLab/cyberdog_ws#5]
我从小米论坛一路跳转到这个codebase。   据说这个是支持cyberdog2的， 但我看readme中并没有提及cyberdog2？

**Comment by ruheng** [comment]
这个是cyberdog2的开源代码

**Comment by lewnus** [comment]
> 这个是cyberdog2的开源代码

感谢答复。 那请问这个codebase能在一代上用吗？  还是说一代只能用cyberdog_ros2那个项目？
